[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "cryptoconditions>=0.8.1",
    "xrpl-py>=4.1.0",
]
